sudo: required
dist: trusty
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - sudo apt-get install dpkg-dev dh-python python-setuptools python3-setuptools python3-all debhelper quilt
  - pip install -r REQUIREMENTS
  - for file in intelmq/bots/*/*/REQUIREMENTS.txt; do pip install -r $file; done
  - pip install coveralls
  - pip install codecov
  - pip install pep8
  - sudo pip install .
  - sudo cp /opt/intelmq/etc/examples/* /opt/intelmq/etc/
before_script:
  - psql -c "CREATE DATABASE intelmq;" -U postgres
  - psql -c "CREATE USER intelmq WITH PASSWORD 'intelmq';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE intelmq TO intelmq;" -U postgres
  - intelmq_psql_initdb
  - sed -i 's/events/tests/' /tmp/initdb.sql
  - psql -v ON_ERROR_STOP=on -f /tmp/initdb.sql intelmq -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO intelmq;" -U postgres
script:
  - nosetests --with-coverage --cover-package=intelmq
  - dpkg-buildpackage -us -uc
  - pep8 intelmq/{bots,lib,bin}
services:
  - redis-server
  - postgresql
after_success:
  - codecov
  - coveralls
addons:
  postgresql: "9.4"
